/**
 * WASM Bindings / Krypto-Wrapper
 *
 * Loads the wasm-pack generated crypto-core module and exposes
 * typed wrappers for the rest of the app.
 *
 * The raw WASM module is generated by:
 *   npm run wasm:build
 * which runs:
 *   wasm-pack build --target web --out-dir ../../web/src/wasm
 */

// wasm-pack --target web generates a self-contained JS glue file.
// We pass the WASM binary URL explicitly so Vite can resolve it as an asset.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — generated file
import init, * as CryptoCore from "./wasm/crypto_core.js";
// ?url tells Vite to give us the resolved URL of the binary (no plugin needed)
import wasmUrl from "./wasm/crypto_core_bg.wasm?url";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _module: typeof CryptoCore | null = null;

/**
 * Initialize the WASM module. Must be called before any crypto function.
 * Safe to call multiple times — subsequent calls are no-ops.
 */
export async function initCrypto(): Promise<void> {
  if (_module !== null) return;
  await init(wasmUrl);
  _module = CryptoCore as typeof CryptoCore;
}

/**
 * Returns the initialized WASM module.
 * Throws if `initCrypto()` has not been awaited first.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getCryptoModule(): any {
  if (_module === null) {
    throw new Error("Crypto module not initialized — call initCrypto() first");
  }
  return _module;
}

// ---------------------------------------------------------------------------
// Typed wrappers (filled in during Phase 2)
// ---------------------------------------------------------------------------

export interface Keypair {
  publicKey: Uint8Array;
  diffieHellman(theirPublicKey: Uint8Array): Uint8Array;
  free(): void;
}

export function generateKeypair(): Keypair {
  return new (getCryptoModule().Keypair)();
}

export function deriveEncryptionKey(
  sharedSecret: Uint8Array,
  salt: Uint8Array
): Uint8Array {
  return getCryptoModule().deriveEncryptionKey(sharedSecret, salt);
}

export function deriveKeyMaterial(
  sharedSecret: Uint8Array,
  salt: Uint8Array
): Uint8Array {
  return getCryptoModule().deriveKeyMaterial(sharedSecret, salt);
}

export function encryptChunk(
  key: Uint8Array,
  nonceSeed: Uint8Array,
  chunkIndex: number,
  plaintext: Uint8Array
): Uint8Array {
  return getCryptoModule().encryptChunk(key, nonceSeed, chunkIndex, plaintext);
}

export function decryptChunk(
  key: Uint8Array,
  nonceSeed: Uint8Array,
  chunkIndex: number,
  ciphertext: Uint8Array
): Uint8Array {
  return getCryptoModule().decryptChunk(key, nonceSeed, chunkIndex, ciphertext);
}

export function blake3Hash(data: Uint8Array): Uint8Array {
  return getCryptoModule().blake3Hash(data);
}

export function hashChunk(data: Uint8Array, index: number): Uint8Array {
  return getCryptoModule().hashChunk(data, index);
}

export function computeMerkleRoot(leafHashes: Uint8Array[]): Uint8Array {
  return getCryptoModule().computeMerkleRoot(leafHashes);
}
